import crafttweaker.api.GenericRecipesManager;
import mods.jei.JEI;
import crafttweaker.api.text.ChatFormatting;

JEI.addDescription(<item:chemlib:element_helium>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:element_lithium>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:element_beryllium>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:element_boron>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:element_carbon>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:element_nitrogen>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:element_oxygen>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:element_fluorine>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:element_neon>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:element_sodium>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:element_magnesium>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:element_aluminum>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:element_silicon>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:element_phosphorus>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:element_sulfur>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:element_chlorine>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:element_argon>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:element_potassium>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:element_calcium>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:element_scandium>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:element_titanium>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:element_vanadium>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:element_chromium>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:element_manganese>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:element_iron>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:element_cobalt>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:element_nickel>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:element_copper>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:element_zinc>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:element_gallium>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:element_germanium>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:element_arsenic>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:element_selenium>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:element_bromine>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:element_krypton>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:element_rubidium>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:element_strontium>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:element_yttrium>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:element_zirconium>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:element_niobium>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:element_molybdenum>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:element_technetium>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:element_ruthenium>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:element_rhodium>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:element_palladium>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:element_silver>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:element_cadmium>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:element_indium>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:element_tin>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:element_antimony>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:element_tellurium>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:element_iodine>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:element_xenon>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:element_cesium>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:element_barium>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:element_lanthanum>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:element_cerium>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:element_praseodymium>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:element_neodymium>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:element_promethium>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:element_samarium>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:element_europium>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:element_gadolinium>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:element_terbium>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:element_dysprosium>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:element_holmium>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:element_erbium>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:element_thulium>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:element_ytterbium>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:element_lutetium>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:element_hafnium>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:element_tantalum>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:element_tungsten>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:element_rhenium>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:element_osmium>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:element_iridium>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:element_platinum>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:element_gold>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:element_mercury>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:element_thallium>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:element_lead>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:element_bismuth>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:element_polonium>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:element_astatine>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:element_radon>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:element_francium>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:element_radium>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:element_actinium>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:element_thorium>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:element_protactinium>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:element_uranium>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:element_neptunium>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:element_plutonium>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:element_americium>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:element_curium>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:element_berkelium>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:element_californium>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:element_einsteinium>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:element_fermium>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:element_mendelevium>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:element_nobelium>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:element_lawrencium>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:element_rutherfordium>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:element_dubnium>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:element_seaborgium>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:element_bohrium>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:element_hassium>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:element_meitnerium>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:element_darmstadtium>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:element_roentgenium>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:element_copernicium>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:element_nihonium>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:element_flerovium>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:element_moscovium>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:element_livermorium>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:element_tennessine>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");
JEI.addDescription(<item:chemlib:element_oganesson>,"All elements (except Hydrogen) can be created with the Fusion Chamber multiblock.\\nThe multiblock accepts 2 elements as input and fuses them together to create a new element equal to the sum of their atomic numbers.\"");


JEI.hideCategory("jeresources:enchantment");

JEI.hideIngredient(<item:exnihilosequentia:andesite_pebble>);
JEI.hideIngredient(<item:exnihilosequentia:basalt_pebble>);
JEI.hideIngredient(<item:exnihilosequentia:blackstone_pebble>);
JEI.hideIngredient(<item:exnihilosequentia:diorite_pebble>);
JEI.hideIngredient(<item:exnihilosequentia:granite_pebble>);
JEI.hideIngredient(<item:exnihilosequentia:stone_pebble>);
JEI.hideIngredient(<item:exnihilosequentia:iron_pieces>);
JEI.hideIngredient(<item:exnihilosequentia:gold_pieces>);
JEI.hideIngredient(<item:exnihilosequentia:copper_pieces>);
JEI.hideIngredient(<item:exnihilosequentia:lead_pieces>);
JEI.hideIngredient(<item:exnihilosequentia:tin_pieces>);
JEI.hideIngredient(<item:exnihilosequentia:uranium_pieces>);
JEI.hideIngredient(<item:exnihilosequentia:platinum_pieces>);
JEI.hideIngredient(<item:exnihilosequentia:silver_pieces>);
JEI.hideIngredient(<item:exnihilosequentia:zinc_pieces>);
JEI.hideIngredient(<item:exnihilosequentia:nickel_pieces>);
JEI.hideIngredient(<item:exnihilosequentia:oak_seeds>);
JEI.hideIngredient(<item:exnihilosequentia:spruce_seeds>);
JEI.hideIngredient(<item:exnihilosequentia:birch_seeds>);
JEI.hideIngredient(<item:exnihilosequentia:blue_coral_larvae>);
JEI.hideIngredient(<item:exnihilosequentia:pink_coral_larvae>);
JEI.hideIngredient(<item:exnihilosequentia:purple_coral_larvae>);
JEI.hideIngredient(<item:exnihilosequentia:red_coral_larvae>);
JEI.hideIngredient(<item:exnihilosequentia:yellow_coral_larvae>);
JEI.hideIngredient(<item:exnihilosequentia:dust>);
JEI.hideIngredient(<item:exnihilosequentia:crushed_netherrack>);
JEI.hideIngredient(<item:exnihilosequentia:crushed_end_stone>);
JEI.hideIngredient(<item:exnihilosequentia:crushed_andesite>);
JEI.hideIngredient(<item:exnihilosequentia:crushed_diorite>);
JEI.hideIngredient(<item:exnihilosequentia:crushed_granite>);
JEI.hideIngredient(<item:exnihilosequentia:blaze_doll>);
JEI.hideIngredient(<item:exnihilosequentia:enderman_doll>);
JEI.hideIngredient(<item:exnihilosequentia:shulker_doll>);
JEI.hideIngredient(<item:exnihilosequentia:guardian_doll>);
JEI.hideIngredient(<item:exnihilosequentia:bee_doll>);
JEI.hideIngredient(<item:exnihilosequentia:diamond_hammer>);
JEI.hideIngredient(<item:exnihilosequentia:golden_hammer>);
JEI.hideIngredient(<item:exnihilosequentia:iron_hammer>);
JEI.hideIngredient(<item:exnihilosequentia:netherite_hammer>);
JEI.hideIngredient(<item:exnihilosequentia:stone_hammer>);
JEI.hideIngredient(<item:exnihilosequentia:wooden_hammer>);
JEI.hideIngredient(<item:exnihilosequentia:acacia_seeds>);
JEI.hideIngredient(<item:exnihilosequentia:jungle_seeds>);
JEI.hideIngredient(<item:exnihilosequentia:end_cake>);
JEI.hideIngredient(<item:exnihilosequentia:jungle_sieve>);
JEI.hideIngredient(<item:exnihilosequentia:oak_sieve>);
JEI.hideIngredient(<item:exnihilosequentia:spruce_sieve>);
JEI.hideIngredient(<item:exnihilosequentia:crimson_sieve>);
JEI.hideIngredient(<item:exnihilosequentia:warped_sieve>);
JEI.hideIngredient(<item:exnihilosequentia:dark_oak_sieve>);
JEI.hideIngredient(<item:exnihilosequentia:birch_sieve>);
JEI.hideIngredient(<item:exnihilosequentia:acacia_sieve>);
JEI.hideIngredient(<item:exnihilosequentia:large_fern_seeds>);
JEI.hideIngredient(<item:exnihilosequentia:string_mesh>);
JEI.hideIngredient(<item:exnihilosequentia:flint_mesh>);
JEI.hideIngredient(<item:exnihilosequentia:iron_mesh>);
JEI.hideIngredient(<item:exnihilosequentia:diamond_mesh>); 
JEI.hideIngredient(<item:exnihilosequentia:emerald_mesh>);
JEI.hideIngredient(<item:exnihilosequentia:netherite_mesh>);
JEI.hideIngredient(<item:exnihilosequentia:fern_seeds>);
JEI.hideIngredient(<item:exnihilosequentia:bamboo_seeds>);
JEI.hideIngredient(<item:exnihilosequentia:pickle_seeds>);
JEI.hideIngredient(<item:exnihilosequentia:kelp_seeds>);
JEI.hideIngredient(<item:exnihilosequentia:sweet_berry_seeds>);
JEI.hideIngredient(<item:exnihilosequentia:potato_seeds>);
JEI.hideIngredient(<item:exnihilosequentia:carrot_seeds>);
JEI.hideIngredient(<item:exnihilosequentia:sugarcane_seeds>);
JEI.hideIngredient(<item:exnihilosequentia:cactus_seeds>);
JEI.hideIngredient(<item:exnihilosequentia:dark_oak_seeds>);
JEI.hideIngredient(<item:exnihilosequentia:mycelium_spores>);
JEI.hideIngredient(<item:exnihilosequentia:grass_seeds>);

JEI.hideIngredient(<item:ae2:facade>);
JEI.hideIngredient(<item:refinedstorage:cover>);
JEI.hideCategory("create:mystery_conversion");
JEI.hideCategory("reliquary:alkahestry_charging");
JEI.hideCategory("reliquary:alkahestry_crafting");

<item:chemlib:element_carbon>.addTooltip("§6Can be used as furnace fuel§r");
<item:chemlib:element_hydrogen>.addTooltip("§6Can be used as furnace fuel§r");
<item:kubejs:new_compound_ethylene>.addTooltip("§3C₂H₄§r");
<item:kubejs:raw_andesite_alloy>.addTooltip("§6§kx§r §4Blood Thirsty§r §6§kx§r");
<item:kubejs:finished_program>.addTooltip("§b§k. §r§bGet back to reality...§r");